defaults: &defaults
  adapter: postgresql
  host: localhost
  encoding: unicode
  username: root
  min_messages: warning

development:
  <<: *defaults
  database: futureiscode_development

test:
  <<: *defaults
  database: futureiscode_test
